"use client";

import {useEffect,useState} from "react";
import {Activity,Bell,CalendarDays,Check,ChevronDown,ChevronRight,CircleDollarSign,CreditCard,FileText,Gauge,HardHat,Home,LayoutDashboard,Menu,MessageSquareText,MoreHorizontal,Plus,Search,Sparkles,Star,Users,WandSparkles,Workflow,Wrench,X,Zap} from "lucide-react";

type View="Command center"|"Dispatch"|"Leads"|"Customers"|"Jobs"|"Payments"|"Automations";
const nav:{label:View;icon:React.ElementType;badge?:string}[]=[{label:"Command center",icon:LayoutDashboard},{label:"Dispatch",icon:CalendarDays,badge:"LIVE"},{label:"Leads",icon:Zap,badge:"12"},{label:"Customers",icon:Users},{label:"Jobs",icon:Wrench,badge:"8"},{label:"Payments",icon:CreditCard},{label:"Automations",icon:Workflow}];
const jobs=[{time:"8:00",duration:"2h",customer:"Maya Thompson",service:"AC repair",tech:"Jordan",color:"blue",area:"Lakeview"},{time:"9:30",duration:"1.5h",customer:"Nolan Pierce",service:"Drain cleaning",tech:"Marcus",color:"violet",area:"Riverside"},{time:"11:00",duration:"3h",customer:"Ava Martinez",service:"Panel upgrade",tech:"Theo",color:"orange",area:"Oak Park"},{time:"13:30",duration:"2h",customer:"Ethan Brooks",service:"Water heater",tech:"Jordan",color:"teal",area:"West Loop"}];
const leads=[{initials:"LM",name:"Lena Moore",request:"No cooling upstairs",source:"Missed call",score:96,age:"2m"},{initials:"RB",name:"Rafael Bell",request:"Kitchen sink backing up",source:"Website",score:88,age:"8m"},{initials:"KS",name:"Keisha Stone",request:"EV charger installation",source:"Google",score:82,age:"14m"}];
const pipeline=[{label:"New lead",value:12,color:"#5b5cf0"},{label:"Qualified",value:8,color:"#8d6df5"},{label:"Scheduled",value:6,color:"#27a788"},{label:"In progress",value:4,color:"#f0a33b"},{label:"Completed",value:17,color:"#1f7a65"}];

export function HomeServeApp(){const[view,setView]=useState<View>("Command center");const[sidebar,setSidebar]=useState(false);const[modal,setModal]=useState<"job"|"ai"|null>(null);const[toast,setToast]=useState("");const[automationOn,setAutomationOn]=useState(true);useEffect(()=>{if(!modal)return;function handleKeyDown(event:KeyboardEvent){if(event.key==="Escape"){event.preventDefault();setModal(null)}}window.addEventListener("keydown",handleKeyDown);return()=>window.removeEventListener("keydown",handleKeyDown)},[modal]);function notify(message:string){setToast(message);window.setTimeout(()=>setToast(""),2500)}return <div className="shell">
<aside className={`sidebar ${sidebar?"open":""}`}><div className="brand"><span className="brand-mark"><Home size={17}/></span><strong>HomeServe</strong><em>OS</em><button className="mobile-close" onClick={()=>setSidebar(false)}><X size={18}/></button></div><button className="workspace"><span className="workspace-logo">AH</span><span><strong>Apex Home Co.</strong><small>Chicago operations</small></span><ChevronDown size={15}/></button><p className="nav-label">OPERATIONS</p><nav>{nav.map(({label,icon:Icon,badge})=><button key={label} className={view===label?"active":""} onClick={()=>{setView(label);setSidebar(false)}}><Icon size={18}/><span>{label}</span>{badge&&<small>{badge}</small>}</button>)}</nav><p className="nav-label">WORKSPACE</p><nav><button><MessageSquareText size={18}/><span>Team inbox</span><small>3</small></button><button><FileText size={18}/><span>Reports</span></button></nav><div className="sidebar-bottom"><div className="growth-card"><Sparkles size={17}/><strong>Growth pulse</strong><span>Revenue is up 18% this month.</span><button onClick={()=>setView("Payments")}>View insights <ChevronRight size={13}/></button></div><div className="profile"><span>EE</span><div><strong>Emmanuel</strong><small>Owner · Admin</small></div><MoreHorizontal size={17}/></div></div></aside>
<main><header className="topbar"><button className="menu" onClick={()=>setSidebar(true)}><Menu size={20}/></button><button className="search"><Search size={17}/><span>Search customers, jobs, invoices…</span><kbd>⌘ K</kbd></button><div className="top-actions"><button className="ai-button" onClick={()=>setModal("ai")}><WandSparkles size={16}/> Ask HomeServe</button><button className="icon-button"><Bell size={19}/><i/></button><button className="avatar">EE</button></div></header><div className="content">{view==="Command center"?<Dashboard setView={setView} setModal={setModal} automationOn={automationOn} setAutomationOn={setAutomationOn} notify={notify}/>:<ModuleView view={view} setModal={setModal} notify={notify}/>}</div></main>
{sidebar&&<div className="backdrop" onClick={()=>setSidebar(false)}/>} {modal&&<Modal type={modal} close={()=>setModal(null)} notify={m=>{setModal(null);notify(m)}}/>}{toast&&<div className="toast"><Check size={17}/>{toast}</div>}</div>}

function Dashboard({setView,setModal,automationOn,setAutomationOn,notify}:{setView:(v:View)=>void;setModal:(m:"job"|"ai")=>void;automationOn:boolean;setAutomationOn:(v:boolean)=>void;notify:(m:string)=>void}){return <><section className="page-heading"><div><div className="eyebrow">TUESDAY, OCTOBER 6 <span>•</span> 72°F</div><h1>Good morning, Emmanuel.</h1><p>Here’s what’s moving across your business today.</p></div><button className="primary" onClick={()=>setModal("job")}><Plus size={17}/> Create job</button></section><section className="metrics"><Metric icon={CircleDollarSign} label="Revenue this month" value="$84,260" delta="18.4%" note="vs. last month" tone="green"/><Metric icon={CalendarDays} label="Jobs today" value="14" delta="3 remaining" note="8 completed" tone="blue"/><Metric icon={Zap} label="Open leads" value="12" delta="4 hot" note="2 need a reply" tone="orange"/><Metric icon={Star} label="Customer rating" value="4.9" delta="+0.2" note="from 248 reviews" tone="violet"/></section>
<section className="dashboard-grid"><article className="panel schedule-panel"><PanelHead title="Today’s dispatch" subtitle="14 jobs · 5 technicians" action="Open dispatch" onAction={()=>setView("Dispatch")}/><div className="schedule"><div className="time-rail">{["8 AM","10 AM","12 PM","2 PM","4 PM"].map(t=><span key={t}>{t}</span>)}</div><div className="job-list">{jobs.map(j=><button key={j.customer} className={`job-card ${j.color}`} onClick={()=>notify(`${j.service} job opened`)}><span className="job-time">{j.time}</span><div><strong>{j.service}</strong><p>{j.customer} · {j.area}</p></div><span className="tech">{j.tech[0]}</span><small>{j.duration}</small></button>)}</div></div></article>
<article className="panel leads-panel"><PanelHead title="New opportunities" subtitle="AI-ranked by booking intent" action="View all" onAction={()=>setView("Leads")}/><div className="lead-list">{leads.map(l=><button className="lead" key={l.name} onClick={()=>setView("Leads")}><span className="lead-avatar">{l.initials}</span><div><strong>{l.name}</strong><p>{l.request}</p><small>{l.source} · {l.age} ago</small></div><span className="score"><Sparkles size={12}/>{l.score}</span><ChevronRight size={15}/></button>)}</div><button className="ai-summary" onClick={()=>setModal("ai")}><span><WandSparkles size={18}/></span><div><strong>HomeServe AI found $4.8k</strong><p>in likely revenue across today’s new leads</p></div><ChevronRight size={16}/></button></article>
<article className="panel pipeline-panel"><PanelHead title="Customer lifecycle" subtitle="Live pipeline · last 30 days" action="View report" onAction={()=>notify("Lifecycle report ready")}/><div className="pipeline">{pipeline.map((p,i)=><div className="stage" key={p.label}><div className="stage-bar" style={{background:p.color,height:42+(pipeline.length-i)*9}}/><strong>{p.value}</strong><span>{p.label}</span>{i<pipeline.length-1&&<ChevronRight className="stage-arrow" size={15}/>}</div>)}</div><div className="conversion"><span>Lead → booked conversion</span><strong>64.2%</strong><em>+8.1%</em></div></article>
<article className="panel activity-panel"><PanelHead title="Live activity" subtitle="Across Apex Home Co."/><div className="timeline"><ActivityItem icon={CreditCard} title="$1,480 payment received" meta="Invoice #INV-1048 · Maya Thompson" time="2m" tone="green"/><ActivityItem icon={Check} title="Job completed by Jordan" meta="AC repair · Lakeview" time="12m" tone="blue"/><ActivityItem icon={MessageSquareText} title="AI replied to a missed call" meta="Lena Moore · Lead score 96" time="18m" tone="violet"/><ActivityItem icon={Star} title="New 5-star review" meta="“Fast, kind, and incredibly tidy.”" time="31m" tone="orange"/></div></article>
<article className="panel automation-panel"><div className="automation-top"><span className="bolt"><Workflow size={18}/></span><div><strong>Missed-call recovery</strong><p>Your highest-impact automation</p></div><button aria-label="Toggle automation" className={`toggle ${automationOn?"on":""}`} onClick={()=>setAutomationOn(!automationOn)}><i/></button></div><div className="flow"><span>Missed call</span><ChevronRight/><span>AI SMS</span><ChevronRight/><span>Qualify</span><ChevronRight/><span>Book</span></div><div className="automation-stats"><div><strong>38</strong><span>leads recovered</span></div><div><strong>$18.4k</strong><span>revenue influenced</span></div><div><strong>42 sec</strong><span>avg. response</span></div></div></article></section></>}

function ModuleView({view,setModal,notify}:{view:View;setModal:(m:"job"|"ai")=>void;notify:(m:string)=>void}){const descriptions:Record<View,string>={"Command center":"","Dispatch":"Plan routes, balance capacity, and keep every technician moving.","Leads":"Turn every call, form, and message into a booked job.","Customers":"A complete history of every property and conversation.","Jobs":"Track field work from arrival through customer sign-off.","Payments":"Estimates, invoices, payments, and revenue in one place.","Automations":"Build the workflows that run your customer lifecycle."};const icons:Record<View,React.ElementType>={"Command center":Gauge,"Dispatch":CalendarDays,"Leads":Zap,"Customers":Users,"Jobs":HardHat,"Payments":CreditCard,"Automations":Workflow};const Icon=icons[view];return <><section className="page-heading"><div><div className="eyebrow">APEX HOME CO. <span>•</span> OPERATIONS</div><h1>{view}</h1><p>{descriptions[view]}</p></div><button className="primary" onClick={()=>view==="Automations"?notify("Automation builder opened"):setModal("job")}><Plus size={17}/> {view==="Automations"?"New automation":"Create job"}</button></section><section className="module-hero"><div><span className="module-icon"><Icon size={24}/></span><p>HOME SERVICE, CONNECTED</p><h2>{view==="Dispatch"?"The right technician, at the right door, right on time.":view==="Payments"?"From estimate to paid—without chasing paperwork.":`${view} that keeps the customer journey moving.`}</h2><p className="module-copy">Every interaction stays connected to the customer, property, job, and revenue record. This interactive portfolio demo focuses on the full operating workflow.</p><button className="secondary" onClick={()=>notify(`${view} workflow opened`)}>Explore workflow <ChevronRight size={16}/></button></div><div className="module-visual"><div className="orbit"><Icon size={38}/><span className="orbit-dot one"/><span className="orbit-dot two"/><span className="orbit-dot three"/></div></div></section><section className="feature-row"><Feature icon={Users} title="Unified records" text="One timeline for calls, texts, appointments, work, invoices, and reviews."/><Feature icon={Sparkles} title="AI-assisted" text="Qualify leads, summarize conversations, and draft thoughtful follow-ups."/><Feature icon={Activity} title="Operational clarity" text="See ownership, status, SLA risk, and revenue impact in real time."/></section></>}

function Metric({icon:Icon,label,value,delta,note,tone}:{icon:React.ElementType;label:string;value:string;delta:string;note:string;tone:string}){return <article className="metric"><div className={`metric-icon ${tone}`}><Icon size={19}/></div><MoreHorizontal size={17}/><p>{label}</p><strong>{value}</strong><footer><em className={tone}>{delta}</em><span>{note}</span></footer></article>}
function PanelHead({title,subtitle,action,onAction}:{title:string;subtitle:string;action?:string;onAction?:()=>void}){return <header className="panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div>{action&&<button onClick={onAction}>{action}<ChevronRight size={14}/></button>}</header>}
function ActivityItem({icon:Icon,title,meta,time,tone}:{icon:React.ElementType;title:string;meta:string;time:string;tone:string}){return <div className="activity-item"><span className={`activity-icon ${tone}`}><Icon size={15}/></span><div><strong>{title}</strong><p>{meta}</p></div><time>{time}</time></div>}
function Feature({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <article><span><Icon size={20}/></span><h3>{title}</h3><p>{text}</p></article>}

function Modal({type,close,notify}:{type:"job"|"ai";close:()=>void;notify:(m:string)=>void}){return <div className="modal-wrap" role="dialog" aria-modal="true" aria-labelledby="homeserve-dialog-title"><div className="modal"><header><span className={type==="ai"?"ai-modal-icon":"modal-icon"}>{type==="ai"?<Sparkles size={20}/>:<Wrench size={20}/>}</span><div><h2 id="homeserve-dialog-title">{type==="ai"?"Ask HomeServe":"Create a new job"}</h2><p>{type==="ai"?"Your operations copilot, grounded in workspace data.":"Schedule work and assign it to your team."}</p></div><button type="button" aria-label="Close dialog" onClick={close}><X size={18}/></button></header>{type==="ai"?<><div className="ai-response"><p className="ai-prompt">What needs my attention today?</p><div className="thinking"><Sparkles size={17}/><p><strong>Three things stand out:</strong> Lena Moore is a high-intent missed-call lead, the 1:30 PM water-heater job needs a permit photo, and invoice #1042 is four days overdue.</p></div></div><div className="suggestions"><button>Draft Lena’s follow-up</button><button>Show at-risk jobs</button><button>Summarize revenue</button></div><div className="composer"><input aria-label="Ask HomeServe" placeholder="Ask about customers, jobs, or revenue…"/><button onClick={()=>notify("AI response generated")}><Sparkles size={16}/></button></div></>:<><div className="form-grid"><label>Customer<input defaultValue="Lena Moore"/></label><label>Service<select defaultValue="hvac"><option value="hvac">HVAC repair</option><option>Plumbing</option><option>Electrical</option></select></label><label>Date<input type="date" defaultValue="2026-10-07"/></label><label>Arrival window<select><option>8:00 – 10:00 AM</option><option>10:00 AM – 12:00 PM</option></select></label><label className="wide">Service address<input defaultValue="1420 N State St, Chicago, IL"/></label><label>Technician<select><option>Jordan Lee</option><option>Marcus Grant</option></select></label><label>Estimate<input defaultValue="$189.00"/></label></div><footer><button className="ghost" onClick={close}>Cancel</button><button className="primary" onClick={()=>notify("Job created and technician notified")}><Check size={16}/> Create job</button></footer></>}</div></div>}

